export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const EDIT_SERVICE_FIELD = 'EDIT_SERVICE_FIELD';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const FILTER_SERVICES = 'FILTER_SERVICES';